baseurl = "/"
languageCode = "en-us"
theme = "terminal-bio"
paginate = 5

[params]
  contentTypeName = "posts"

  themeColor = "green"

  showMenuItems = 2

  showLanguageSelector = false

  fullWidthTheme = false

  centerTheme = true

  showLastUpdated = false

  singlePageSite = true

  homepagePaginateCount = 2

  homepageNavEntriesDontRender = []


[languages]
  [languages.en]
    languageName = "English"
    title = "Azim Muradov"
    subtitle = "Software Engineer"
    owner = "Azim Muradov"
    keywords = ""
    copyright = "Copyright 2022-{year} Azim Muradov. All Rights Reserved."
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

  [languages.en.params.logo]
    logoText = "Azim Muradov"
      logoHomeLink = "/"
