baseurl = "/"
languageCode = "en-us"
theme = "terminal-bio"
paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

  # Single Page Sites have the links in their navigation menu point to sections on the
  # main-single page. If `singlePageSite` is enabled all nav manu entries will be rendered
  # on the homepage as homepage sections unless their identifier appears in the
  # `homepageNavEntriesDontRender` parameter, in which they will not appear on the homepage.
  # - Nav menu items with a url beginning with "/#" are homepage only sections. These
  #   sections draw their content from the homepage content type directory
  #   (content/homepage/<somesection>.md).
  # - Nav menu items not beginning with "/#" will be also be rendered as sections on the
  #   homepage either as paginated lists (like posts), as regular sections, or taxonomy depending on
  #   what the url is pointing to.
  # The homepage sections may not render in the order that you expect. Use the `weight` menu parameter
  # on the menu entries to make sure the homepage sections appear in the order you like.

  # enable the sngle page site mode described above
  singlePageSite = true

  # for collections rendered on the hompage, you may want them to be paginated at a different
  # (usually smaller) count compared to the actual list pages. Default is 2
  homepagePaginateCount = 0

  # If there is a nav menu entry you dont want rendered on the homepage, add the identifier here
  homepageNavEntriesDontRender = ["showcase"]

  remark42SiteID = "remark"
  remark42Url = "http://185.146.156.232"

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Azim Muradov"
    subtitle = "Software Engineer"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Azim Muradov"
      logoHomeLink = "/"
      # If your logo text is long, you can have it split on a certain substring when the screen is narrow
      # logoSplit = ""

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"