baseurl: /

languageCode: en-us

theme: terminal-bio

paginate: 5

enableEmoji: true


params:
  # --- terminal ---

  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  # contentTypeName: posts

  # ["orange", "blue", "red", "green", "pink"]
  themeColor: green

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 10

  # show selector to switch language
  showLanguageSelector: false

  # set theme to full screen width
  fullWidthTheme: false

  # center theme with default width
  centerTheme: true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  # autoCover: true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated: false

  # set a custom favicon (default is a `themeColor` square)
  # favicon: "favicon.ico"

  oneHeadingSize: false

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  toc: true

  # set title for the table of contents
  # can be overridden in a page's front-matter
  tocTitle: 'Table of Contents'


  # --- terminal - single page website ---

  # Single Page Sites have the links in their navigation menu point to sections on the
  # main-single page. If `singlePageSite` is enabled all nav manu entries will be rendered
  # on the homepage as homepage sections unless their identifier appears in the
  # `homepageNavEntriesDontRender` parameter, in which they will not appear on the homepage.
  # - Nav menu items with a url beginning with "/#" are homepage only sections. These
  #   sections draw their content from the homepage content type directory
  #   (content/homepage/<somesection>.md).
  # - Nav menu items not beginning with "/#" will be also be rendered as sections on the
  #   homepage either as paginated lists (like posts), as regular sections, or taxonomy depending on
  #   what the url is pointing to.
  # The homepage sections may not render in the order that you expect. Use the `weight` menu parameter
  # on the menu entries to make sure the homepage sections appear in the order you like.

  # enable the single page site mode described above
  singlePageSite: true

  # for collections rendered on the homepage, you may want them to be paginated at a different
  # (usually smaller) count compared to the actual list pages. Default is 2
  # homepagePaginateCount: 2

  # If there is a nav menu entry you don't want rendered on the homepage, add the identifier here
  homepageNavEntriesDontRender: [ projects, resume ]


languages:
  en:
    languageName: English
    title: 'Azim Muradov'
    subtitle: 'Software Engineer'
    owner: 'Azim Muradov'
    keywords: ''
    copyright: 'Copyright 2022 Azim Muradov. All Rights Reserved.'
    menuMore: 'Show more'
    readMore: 'Read more'
    readOtherPosts: 'Read other posts'
    newerPosts: 'Newer posts'
    olderPosts: 'Older posts'
    missingContentMessage: 'Page not found...'
    missingBackButtonLabel: 'Back to home page'
    params:
      logo:
        logoText: 'Azim Muradov'
        logoSplit: " / "   # Places logo text blocks in to spans so they wrap nicely
        logoHomeLink: "/"
    menu:
      main:
        - identifier: home
          weight: 1
          name: 'Home'
          url: /#home
        - identifier: projects
          weight: 2
          name: 'Projects'
          url: /projects
